# Config file for Pathogen pipeline

## Run config
threads_max: 40

## Data Locations
sample_dir: /data/storage/dataprocessing/rnaseq_data/Dutch_Microglia/
pathogen_fasta: /data/storix2/brainsamples/pathogenes/pathogens.fna
human_fasta: /data/storix2/brainsamples/human_genome/complete_human_genome.fasta

## Script config
get_genomes: scripts/get_genomes.py
genome_dict_obj: output_dir/genomedict.pkl
accession_to_name: scripts/accession_to_name.py
pileup: /homes/jprofijt/Programs/bbmap/pileup.sh
pileup_mem: 20g
exclude_py: scripts/exclude_0_Allignment.py
get_total: scripts/calculate_unidentified.py

## Constants, can be changed to preference but not recommended

workdir: output_dir/
human_index: output_dir/index/human/
pathogen_index: output_dir/index/pathogen/
sam_dir: output_dir/sam_output/
tmp: output_dir/tmp/
unmapped_dir: output_dir/Unmapped/
log_dir: output_dir/log/
bam_dir: output_dir/bam_output/
mapped_bam: output_dir/bam_output/mapped_bam/
results: output_dir/results/
accession: output_dir/results/accession_numbers/
science_names: output_dir/results/scientific_names/
single_names: output_dir/results/scientific_names/single_names/

## result
## Image size in pixels
result_height: 800
result_width: 1200

## basenames

basenames:
    -   S15018_GTTTCG_L007
    -   S12112_GATCAG_L007
    -   S14005_GGCTAC_L007
    -   S12082_ACTTGA_L007
    -   S1210100_TAGCTT_L007
    -   S12048_ATCACG_L007








