# Config file for Pathogen pipeline

workdir: output_dir/
sample_dir: testdata/testsamples/
pathogen_fasta: testdata/pathogens_head.fna
human_fasta: testdata/complete_human_genome.fasta
genome_dict_obj: output_dir/genomedict.pkl
