# Config file for Pathogen pipeline

workdir: output_dir/
sample_dir: /data/storage/dataprocessing/rnaseq_data/Dutch_Microglia/
genome: /data/storage/storix2/brainsamples/human_genome/complete_human_genome.fasta
pathogen_fasta: testdata/pathogens_head.fna

