# Config file for Pathogen pipeline

workdir: output_dir/
sample_dir: /data/storage/dataprocessing/rnaseq_data/Dutch_Microglia/
pathogen_fasta: testdata/pathogens_head.fna
human_fasta: testdata/complete_human_genome.fasta
